### PR TITLE
feat(recordings): add recording segment generator

### PR DESCRIPTION
**Pull request by bmckerry**
This adds a script to produce dummy recording segments for load testing the recording consumer. 
I heavily based (read: copypasta) the code from what's in sentry's [test_recordings.py](https://github.com/getsentry/sentry/blob/master/tests/sentry/replays/consumers/test_recording.py#L50-L103). 
### Limitations:
- chunked segments are only length 1, if we get rid of chunked messages soon this isn't a huge concern
- the message payload is a fixed length, we should add something to simulate variable messages sizes
- this will need to be changed to handle compressed messages (i.e. not using `json.dumps()`)
- I'm not super familiar with our recording schema

Let me know if anything looks wrong.

### CODE REVIEW

**Review by untitaker — APPROVED** [review]
makes sense to me

**Comment by bmckerry** [comment]
Example messages generated using `fake_kafka_producer`:
```
% python main.py -f settings.yaml -n 10
Settings:
{'num_messages': 10, 'topic_name': 'ingest-replay-recordings', 'repeatable': False, 'kafka': {'bootstrap.servers': '127.0.0.1:9092'}, 'metric_types': {}, 'org_id': 1, 'project_id': 10, 'message': '[{"hello":"world"}]', 'compressed': False, 'dry_run': False}
Sending data...
[{"type": "replay_recording_not_chunked", "replay_id": 0, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.333632, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 1, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.333656, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 2, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.3337018, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 3, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.333718, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]", "replay_id": 4, "project_id": 10, "id": 4, "chunk_index": 0, "type": "replay_recording_chunk", "org_id": 1, "received": 1680190514.3337479, "retention_days": 30, "key_id": 123}, {"type": "replay_recording", "replay_id": 4, "replay_recording": {"chunks": 1, "id": 4}, "project_id": 10, "org_id": 1, "received": 1680190514.333749, "retention_days": 30}]
[{"type": "replay_recording_not_chunked", "replay_id": 5, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.333767, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 6, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.333802, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 7, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.333812, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 8, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.3338199, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
[{"type": "replay_recording_not_chunked", "replay_id": 9, "org_id": 1, "key_id": 123, "project_id": 10, "received": 1680190514.3338282, "retention_days": 30, "payload": "{\"segment_id\":1}\n[{\"hello\":\"world\"}]"}]
Flushing !!! 
Done!
```

**Review by tonyo — APPROVED** [review]
🏄

**Review by JoshFerge — APPROVED** [review]
🚀

**Pull request merged**
